"""Make course fields nullable

Revision ID: 549a0d7e6f50
Revises: 8ca8d36333cf
Create Date: 2026-03-31 13:11:00.063465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549a0d7e6f50'
down_revision = '8ca8d36333cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('short_desc',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('full_desc',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('background_image_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('background_image_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('full_desc',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('short_desc',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
